name: Deploy API on Heroku

on:
  push:
    branches: ["main"]

env:
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Docker Container Deploy
        uses: lucassarcanjo/heroku-deploy@2.1.17
        with:
          email: ${{ env.HEROKU_EMAIL }}
          api_key: ${{ env.HEROKU_API_KEY }}
          app_name: ${{ env.HEROKU_APP_NAME }}
          dockerfile_path: ./Dockerfile
